# Generated by Django 4.2.6 on 2023-10-27 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeehistory',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
        migrations.AlterField(
            model_name='employeehistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
